version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/*/action.yml"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆️
    cooldown:
      default-days: 45
