name: CI Lint
permissions: { }

on:
  push:
    branches: [ main, master ]
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  lint:
    uses: ./.github/workflows/workflow-linter.yml
    permissions:
      security-events: write
    with:
      tools: actionlint,zizmor
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
